on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:

      - name: Checkout code
        uses: actions/checkout@master

      - name: Run Roadmap Quality Analysis
        uses: oshliaer/roadmap-quality-gate@fix_inputs
        with:
          google_api_key: ${{ secrets.GOOGLE_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

